import { PlannerService } from '../services/PlannerService';
import { IBucketFilter } from '../models/IPlannerModels';

export interface IPlannerGanttProps {
  planId: string;
  planTitle: string;
  showTitle: boolean;
  viewMode: string;
  showCompletedTasks: boolean;
  showBucketsAsPhases: boolean;
  colorBarsByStatus: boolean;
  sortTasksByStartDate: boolean;
  sortBucketsByStartDate: boolean;
  showTaskNameOnBar: boolean;
  showCurrentDateLine: boolean;
  showStartDateColumn: boolean;
  showEndDateColumn: boolean;
  showAssigneeColumn: boolean;
  showLabelColumn: boolean;
  defaultZoomLevel: number;
  showZoomControl: boolean;
  showPrintButton: boolean;
  showAssigneeFilter: boolean;
  showLabelFilter: boolean;
  showCompletedFilterControl: boolean;
  scrollToToday: boolean;
  scrollToTodayMarginUnits: number;
  showTaskInfoIcon: boolean;
  showInfoDescription: boolean;
  showInfoStartDate: boolean;
  showInfoEndDate: boolean;
  showInfoAssignee: boolean;
  showInfoStatus: boolean;
  showInfoComments: boolean;
  bucketFilter?: IBucketFilter;
  isDarkTheme: boolean;
  themePrimary: string;
  themeSecondary: string;
  themeGrey: string;
  plannerService: PlannerService;
}
