define([], function() {
  return {
    "PropertyPaneDescription": "Choose a Planner plan and how its tasks should be displayed.",
    "BasicGroupName": "Plan",
    "PlanFieldLabel": "Plan",
    "ShowTitleFieldLabel": "Show title",
    "DisplayGroupName": "Display",
    "ViewModeFieldLabel": "Zoom level",
    "ViewModeDay": "Day",
    "ViewModeWeek": "Week",
    "ViewModeMonth": "Month",
    "ShowCompletedFieldLabel": "Show completed tasks by default",
    "ShowBucketsAsPhasesFieldLabel": "Show buckets as phases",
    "SortBucketsByStartDateFieldLabel": "Bucket order",
    "SortBucketsByStartDateOnText": "By earliest start date",
    "SortBucketsByStartDateOffText": "Planner board order",
    "SortTasksByStartDateFieldLabel": "Sort tasks by start date",
    "ColorBarsByStatusFieldLabel": "Color bars by status (not started / in progress / done)",
    "ShowTaskNameOnBarFieldLabel": "Show task name on bars",
    "ShowCurrentDateLineFieldLabel": "Highlight today's date",
    "ScrollToTodayFieldLabel": "Open scrolled to today",
    "ScrollToTodayMarginFieldLabel": "Margin before today (in zoom periods)",
    "ZoomSliderLabel": "Zoom",
    "ZoomUnitDay": "days",
    "ZoomUnitWeek": "weeks",
    "ZoomUnitMonth": "months",
    "AssigneeFilterLabel": "Assigned to",
    "AllAssigneesOption": "Everyone",
    "UnassignedOption": "Unassigned",
    "PrintButtonLabel": "Print / export to PDF",
    "ColumnsGroupName": "Columns",
    "ShowStartDateColumnFieldLabel": "Start date",
    "ShowEndDateColumnFieldLabel": "Due date",
    "ShowAssigneeColumnFieldLabel": "Assigned to",
    "ShowLabelColumnFieldLabel": "Label",
    "ColumnNameHeader": "Name",
    "ColumnStartHeader": "Start",
    "ColumnEndHeader": "Finish",
    "ColumnAssigneeHeader": "Assigned to",
    "ColumnLabelHeader": "Label",
    "ToolbarGroupName": "Viewer toolbar",
    "DefaultZoomLevelFieldLabel": "Default zoom level (periods visible)",
    "ShowZoomControlFieldLabel": "Show zoom slider",
    "ShowAssigneeFilterFieldLabel": "Show \"Assigned to\" filter",
    "ShowLabelFilterFieldLabel": "Show label filter",
    "LabelFilterLabel": "Label",
    "AllLabelsOption": "All labels",
    "NoLabelOption": "No label",
    "ShowPrintButtonFieldLabel": "Show print / export button",
    "ShowCompletedFilterControlFieldLabel": "Show \"completed tasks\" toggle",
    "CompletedTasksToggleLabel": "Tasks",
    "CompletedTasksToggleOnText": "All tasks",
    "CompletedTasksToggleOffText": "Hide completed",
    "OpenInPlannerLabel": "Open in Planner",
    "TaskInfoGroupName": "Task info popup",
    "ShowTaskInfoIconFieldLabel": "Show info icon on tasks",
    "ShowInfoDescriptionFieldLabel": "Show task description",
    "ShowInfoStartDateFieldLabel": "Show start date",
    "ShowInfoEndDateFieldLabel": "Show due date",
    "ShowInfoAssigneeFieldLabel": "Show assigned to",
    "ShowInfoStatusFieldLabel": "Show status",
    "ShowInfoCommentsFieldLabel": "Show comments",
    "TaskInfoButtonTitle": "More info",
    "TaskInfoLoadingLabel": "Loading...",
    "TaskInfoNoDescriptionLabel": "No description.",
    "TaskInfoStartLabel": "Start:",
    "TaskInfoEndLabel": "Due:",
    "TaskInfoAssigneeLabel": "Assigned to:",
    "TaskInfoStatusLabel": "Status:",
    "TaskInfoCommentsHeading": "Comments",
    "TaskInfoNoCommentsLabel": "No comments yet.",
    "TaskInfoUnknownAuthorLabel": "Someone",
    "StatusNotStartedLabel": "Not started",
    "StatusInProgressLabel": "In progress",
    "StatusCompletedLabel": "Completed",
    "BucketsGroupName": "Buckets to show",
    "LoadingBucketsLabel": "Loading buckets...",
    "ErrorLoadingBucketsLabel": "Couldn't load buckets for this plan.",
    "NoBucketsLabel": "This plan has no buckets yet.",
    "LoadingPlansLabel": "Loading your plans...",
    "ErrorLoadingPlansLabel": "Couldn't load plans. Check your Microsoft Graph permissions.",
    "NoPlanSelectedLabel": "Edit this web part and choose a Planner plan to display.",
    "LoadingTasksLabel": "Loading tasks...",
    "ErrorLoadingTasksLabel": "Couldn't load tasks for this plan.",
    "NoTasksFoundLabel": "This plan has no tasks to display yet.",
    "NoTasksMatchFilterLabel": "No tasks are assigned to this person in the current view."
  }
});
