define([], function() {
  return {
    "PropertyPaneDescription": "Choose a Planner plan and how its tasks should be displayed.",
    "BasicGroupName": "Plan",
    "PlanFieldLabel": "Plan",
    "DisplayGroupName": "Display",
    "ViewModeFieldLabel": "Zoom level",
    "ViewModeHour": "Hour",
    "ViewModeQuarterDay": "6 hours",
    "ViewModeHalfDay": "12 hours",
    "ViewModeDay": "Day",
    "ViewModeWeek": "Week",
    "ViewModeMonth": "Month",
    "ShowCompletedFieldLabel": "Show completed tasks",
    "ShowBucketsAsPhasesFieldLabel": "Show buckets as phases",
    "SortTasksByStartDateFieldLabel": "Sort tasks by start date",
    "ColorBarsByStatusFieldLabel": "Color bars by status (not started / in progress / done)",
    "ShowTaskNameOnBarFieldLabel": "Show task name on bars",
    "ShowCurrentDateLineFieldLabel": "Highlight today's date",
    "ZoomSliderLabel": "Zoom",
    "AssigneeFilterLabel": "Assigned to",
    "AllAssigneesOption": "Everyone",
    "UnassignedOption": "Unassigned",
    "ColumnsGroupName": "Columns",
    "ShowStartDateColumnFieldLabel": "Start date",
    "ShowEndDateColumnFieldLabel": "Due date",
    "ShowAssigneeColumnFieldLabel": "Assigned to",
    "ColumnNameHeader": "Name",
    "ColumnStartHeader": "Start",
    "ColumnEndHeader": "Finish",
    "ColumnAssigneeHeader": "Assigned to",
    "BucketsGroupName": "Buckets to show",
    "LoadingBucketsLabel": "Loading buckets...",
    "ErrorLoadingBucketsLabel": "Couldn't load buckets for this plan.",
    "NoBucketsLabel": "This plan has no buckets yet.",
    "LoadingPlansLabel": "Loading your plans...",
    "ErrorLoadingPlansLabel": "Couldn't load plans. Check your Microsoft Graph permissions.",
    "NoPlanSelectedLabel": "Edit this web part and choose a Planner plan to display.",
    "LoadingTasksLabel": "Loading tasks...",
    "ErrorLoadingTasksLabel": "Couldn't load tasks for this plan.",
    "NoTasksFoundLabel": "This plan has no tasks to display yet.",
    "NoTasksMatchFilterLabel": "No tasks are assigned to this person in the current view."
  }
});
