declare interface IPlannerGanttWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  PlanFieldLabel: string;
  CustomTitleFieldLabel: string;
  ShowTitleFieldLabel: string;
  DisplayGroupName: string;
  ViewModeFieldLabel: string;
  ViewModeDay: string;
  ViewModeWeek: string;
  ViewModeMonth: string;
  ShowCompletedFieldLabel: string;
  ShowBucketsAsPhasesFieldLabel: string;
  SortBucketsByStartDateFieldLabel: string;
  SortBucketsByStartDateOnText: string;
  SortBucketsByStartDateOffText: string;
  SortTasksByStartDateFieldLabel: string;
  ColorBarsByStatusFieldLabel: string;
  ShowTaskNameOnBarFieldLabel: string;
  ShowCurrentDateLineFieldLabel: string;
  ScrollToTodayFieldLabel: string;
  ScrollToTodayMarginFieldLabel: string;
  ZoomSliderLabel: string;
  ZoomUnitDay: string;
  ZoomUnitWeek: string;
  ZoomUnitMonth: string;
  AssigneeFilterLabel: string;
  AllAssigneesOption: string;
  UnassignedOption: string;
  PrintButtonLabel: string;
  ColumnsGroupName: string;
  ShowStartDateColumnFieldLabel: string;
  ShowEndDateColumnFieldLabel: string;
  ShowAssigneeColumnFieldLabel: string;
  ColumnNameHeader: string;
  ColumnStartHeader: string;
  ColumnEndHeader: string;
  ColumnAssigneeHeader: string;
  ToolbarGroupName: string;
  DefaultZoomLevelFieldLabel: string;
  ShowZoomControlFieldLabel: string;
  ShowAssigneeFilterFieldLabel: string;
  ShowPrintButtonFieldLabel: string;
  ShowCompletedFilterControlFieldLabel: string;
  CompletedTasksToggleLabel: string;
  CompletedTasksToggleOnText: string;
  CompletedTasksToggleOffText: string;
  OpenInPlannerLabel: string;
  BucketsGroupName: string;
  LoadingBucketsLabel: string;
  ErrorLoadingBucketsLabel: string;
  NoBucketsLabel: string;
  LoadingPlansLabel: string;
  ErrorLoadingPlansLabel: string;
  NoPlanSelectedLabel: string;
  LoadingTasksLabel: string;
  ErrorLoadingTasksLabel: string;
  NoTasksFoundLabel: string;
  NoTasksMatchFilterLabel: string;
}

declare module 'PlannerGanttWebPartStrings' {
  const strings: IPlannerGanttWebPartStrings;
  export = strings;
}
